// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Training_Backend_Dever._18_09_2023_Db_Connection_And_ORM_Introduce.Data;

#nullable disable

namespace Training_Backend_Dever.Migrations
{
    [DbContext(typeof(TestContext))]
    [Migration("20231002112802_M2_More_Table")]
    partial class M2_More_Table
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Training_Backend_Dever._18_09_2023_Db_Connection_And_ORM_Introduce.Data.Entities.ClassRoomEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasDefaultValueSql("NEWID()");

                    b.Property<string>("ClassroomNumber")
                        .IsRequired()
                        .HasColumnType("VARCHAR(5)");

                    b.HasKey("Id");

                    b.ToTable("Classroom", (string)null);
                });

            modelBuilder.Entity("Training_Backend_Dever._18_09_2023_Db_Connection_And_ORM_Introduce.Data.Entities.StudentEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasDefaultValueSql("NEWID()");

                    b.Property<Guid>("ClassroomId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("StudentName")
                        .IsRequired()
                        .HasColumnType("NVARCHAR(50)");

                    b.HasKey("Id");

                    b.HasIndex("ClassroomId");

                    b.ToTable("Student", (string)null);
                });

            modelBuilder.Entity("Training_Backend_Dever._18_09_2023_Db_Connection_And_ORM_Introduce.Data.Entities.StudentEntity", b =>
                {
                    b.HasOne("Training_Backend_Dever._18_09_2023_Db_Connection_And_ORM_Introduce.Data.Entities.ClassRoomEntity", "ClassRoomEntity")
                        .WithMany("StudentEntities")
                        .HasForeignKey("ClassroomId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ClassRoomEntity");
                });

            modelBuilder.Entity("Training_Backend_Dever._18_09_2023_Db_Connection_And_ORM_Introduce.Data.Entities.ClassRoomEntity", b =>
                {
                    b.Navigation("StudentEntities");
                });
#pragma warning restore 612, 618
        }
    }
}
